<?php

use Drupal\image\Entity\ImageStyle;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function gnfac_advisory_theme() {
  $theme['gnfac_advisory_page_theme'] = [
    'variables' => ['from' => NULL, 'to' => NULL],
    'template' => 'd8-theme-page',
  ];

  return $theme;
}

function gnfac_advisory_bridgers($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';

	$offsets = array(
	0=>19,
	1=>27,
	2=>35,
	3=>43

	);

	$offsets2 = array(
	  0 => 20,
	  1 => 29,
	  2 => 38,
	  3 => 47,
	  4 => 56,
	  5 => 65

	);
	$transforms2 = array( '4' => 'gnfac_cardinal_wind_dir');
	$transforms = array( );

	$precip_history = gnfac_get_history_precip('field_bridgers_precip');
	$rows = gnfac_fetch_rpt_file("/home/jimurl/public_html/data/BRID48.RPT" , $offsets,$transforms, TRUE, TRUE);
	$rows2 = gnfac_fetch_rpt_file("/home/jimurl/public_html/data/RIDGE48.RPT" , $offsets2,$transforms2, TRUE, TRUE);
	$time =  str_replace( ' ', '/' ,trim($rows[0]['data'][0])) .' at '.  substr($rows[0]['data'][1], 0, -3 )  .':'. substr($rows[0]['data'][1], -3 );
	$time2 =    str_replace( ' ', '/' ,trim($rows2[0]['data'][0])). ' at '. substr($rows2[0]['data'][1], 0, -3 )  .':'. substr($rows2[0]['data'][1], -3 );
	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .= gnfac_precip_history_block($precip_history);
	


	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/bridger-lift">Bridger Lift</a> ';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '7500&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0]['data'][2] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. $rows[0]['data'][3]. '&#8243;<span class = "data-sub">New</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/bridger/ridge">Bridger Ridge</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9000&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class = "details">'. substr($rows2[0]['data'][4],0 , strpos($rows2[0]['data'][4],'-')).  ' - '. $rows2[0]['data'][3] .'<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows2[0]['data'][5].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
  $markup .= gnfac_advisory_region_body($advisory, 23, 'lon=-110.9213292039456&lat=45.80593584224556' , $title , "<a href ='https://bridgerbowl.com/weather/webcams' target = '_blank'>Bridger Bowl Webcams</a>");
  return $markup;
}


function gnfac_advisory_n_gallatin($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';
	$transforms = array( '6' => 'gnfac_cardinal_wind_dir');
	$precip_history = gnfac_get_history_precip('field_northern_gallatin_precip');
	
	$rows = gnfac_fetch_hobo_file('ngallatin','300234063416550',$transforms, TRUE); // Flanders Mountain weather data
	$rows2 = gnfac_fetch_nrcs_snotel_data('754' , TRUE);
	
	$time =   substr($rows[0][0], 0, 5 )  .' at '. substr($rows[0][1], -5 );
	$time2 =    str_replace( '-', '/' ,substr( trim($rows2[0][0] ), 5 , 5 )) . ' at ' . substr( trim($rows2[0][0] ), 10 );

	
	
	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .=  gnfac_precip_history_block($precip_history);


	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href ="/weather/stations/hyalite-weather-station">Flanders Mountain</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9900&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0][2] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. substr($rows[0][6], 0 , strpos($rows[0][6] , '-' ) )  .' - ' . $rows[0][4]. '<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows[0][5].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/shower-falls-snotel-site">Shower Falls SNOTEL</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '8100&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows2[0][4] . '&#x2109;</td></tr>';

	$markup .=       '<tr><td class = "details">'. $rows2[0][2].'&#8243; <span class = "data-sub">Depth</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
	
	
  $markup .= gnfac_advisory_region_body($advisory, 25, 'lon=-110.98519999999996&lat=45.46195413858578', $title ,
	  "<a href = 'https://www.webviewcams.com/america/montana/bozeman-montana-state-university' target = '_blank' >MSU, Bozeman Webcams</a>" );
	// */
			return  $markup;
}

function gnfac_advisory_s_gallatin($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';	
	$transforms = array( '6' => 'gnfac_cardinal_wind_dir');
	$precip_history = gnfac_get_history_precip('field_southern_gallatin_precip');
	
	$rows = gnfac_fetch_hobo_file('ngallatin','300234063416550',$transforms, TRUE); // Flanders Mountain weather data
	$rows2 = gnfac_fetch_nrcs_snotel_data('754' , TRUE);
	
	$time =   substr($rows[0][0], 0, 5 )  .' at '. substr($rows[0][1], -5 );
	$time2 =    str_replace( '-', '/' ,substr( trim($rows2[0][0] ), 5 , 5 )) . ' at ' . substr( trim($rows2[0][0] ), 10 );

	
	
	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .=  gnfac_precip_history_block($precip_history);

	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href ="/weather/stations/hyalite-weather-station">Flanders Mountain</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9900&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0][2] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. substr($rows[0][6], 0 , strpos($rows[0][6] , '-' ) )  .' - ' . $rows[0][4]. '<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows[0][5].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/shower-falls-snotel-site">Shower Falls SNOTEL</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '8100&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows2[0][4] . '&#x2109;</td></tr>';

	$markup .=       '<tr><td class = "details">'. $rows2[0][2].'&#8243; <span class = "data-sub">Depth</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
	
	
  $markup .= gnfac_advisory_region_body($advisory, 27, 'lon=-111.0984325073243&lat=45.08282136429102', $title ,
	  "<a href = 'https://www.nps.gov/yell/learn/photosmultimedia/webcams.htm' target = '_blank' >Yellowstone NP Webcams</a>"  );
	// */
			return  $markup;
}

function gnfac_advisory_n_madison($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';
	
	$precip_history = gnfac_get_history_precip('field_northern_madison_precip');
	
$transforms = array( '3' => 'gnfac_cardinal_wind_dir' , '6' => 'gnfac_cardinal_wind_dir');
$offsets = array(
0=>10,
1=>16,
2=>22,
3=>28,
4=>34,
5=>40,
6=>46,
7=>53,
8=>58,
9=>64,
10=>71
);
	
	$rows = gnfac_fetch_rpt_file("http://yellowstoneclub.com/reports/TIM1HR.RPT", $offsets, $transforms, TRUE ,  TRUE);
		$rows2 = gnfac_fetch_nrcs_snotel_data('590' , TRUE);
	$time =      str_replace( ' ', '/' ,trim($rows[0]['data'][0])) .' at ' . substr($rows[0]['data'][1], 0, -2 )  .':'. substr($rows[0]['data'][1], -2 );
	$time2 =    str_replace( '-', '/' ,substr( trim($rows2[0][0] ), 5 , 5 )) . ' at ' . substr( trim($rows2[0][0] ), 10 );
;
	
	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .=  gnfac_precip_history_block($precip_history);

	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href ="/weather/yellowstoneclub/timber">Timberline Station</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9400&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0]['data'][8] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. substr($rows[0]['data'][3], 0 , strpos($rows[0]['data'][3] , '-' ) )  .' - ' . $rows[0]['data'][2]. '<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows[0]['data'][4].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/lone-mountain">Lone Mountain SNOTEL</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '8880&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows2[0][4] . '&#x2109;</td></tr>';

	$markup .=       '<tr><td class = "details">'. $rows2[0][2].'&#8243; <span class = "data-sub">Depth</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
  $markup .= gnfac_advisory_region_body($advisory, 24, 'lon=-111.37391198351382&lat=45.332802563598165', $title ,
	  "<a href = 'https://bigskyresort.com/the-mountain/webcams' target = '_blank' >Big Sky Webcams</a></br>".
	  "<a href = 'http://www.bigskytowncenter.com/webcam/' target = '_blank' >Big Sky Town Center Webcams</a></br>".
	  "<a href = 'http://yellowstone-club.terrafox.io/mtn-1/' target = '_blank' >Yellowstone Club Webcams</a></br>");
	// */
	return  $markup;
}

function gnfac_advisory_s_madison($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';
	$transforms = array( '6' => 'gnfac_cardinal_wind_dir');
	$precip_history = gnfac_get_history_precip('field_southern_madison_precip');
	
	$rows = gnfac_fetch_hobo_file('taylor_fork', '300234010341360', $transforms, TRUE);
	$rows2 = gnfac_fetch_nrcs_snotel_data('385' , TRUE);
	$time =   substr($rows[0][0], 0, 5 )  .' at '. substr($rows[0][1], -5 );
	$time2 =    str_replace( '-', '/' ,substr( trim($rows2[0][0] ), 5 , 5 )) . ' at ' . substr( trim($rows2[0][0] ), 10 );
	
	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .=  gnfac_precip_history_block($precip_history);

	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href ="/weather/stations/taylor-fork">Taylor Fork</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9460&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0][2] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. substr($rows[0][6], 0 , strpos($rows[0][6] , '-' ) )  .' - ' . $rows[0][4]. '<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows[0][5].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/carrot-basin">Carrot Basin SNOTEL</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9000&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows2[0][4] . '&#x2109;</td></tr>';

	$markup .=       '<tr><td class = "details">'. $rows2[0][2].'&#8243; <span class = "data-sub">Depth</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
  $markup .= gnfac_advisory_region_body($advisory, 26, 'lon=-111.2721355117673&lat=44.98236153381072', $title  );
	// */
	return  $markup;
}

function gnfac_advisory_lionhead($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';	
	$offsets = array(0=>13,1=>21, 2=>29, 3=>37, 4=>45, 5=>53, 6=>61, 7=>69, 8=>77 );
  $transforms = array( '5' => 'gnfac_cardinal_wind_dir' );
	$precip_history = gnfac_get_history_precip('field_lionhead_precip');

  $rows = gnfac_fetch_rpt_file("/home/jimurl/public_html/data/LH48.RPT" , $offsets, $transforms, TRUE, TRUE );
	$rows2 = gnfac_fetch_nrcs_snotel_data('609' , TRUE);

	$time =      str_replace( ' ', '/' ,trim($rows[0]['data'][0])) .' at ' . substr($rows[0]['data'][1], 0, -2 )  .':'. substr($rows[0]['data'][1], -2 );
	$time2 =    str_replace( '-', '/' ,substr( trim($rows2[0][0] ), 5 , 5 )) . ' at ' . substr( trim($rows2[0][0] ), 10 );
	
	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .=  gnfac_precip_history_block($precip_history);

	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href ="/weather/stations/lionhead-weather-station">Lionhead Weather Station</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '8243&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0]['data'][2] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. substr($rows[0]['data'][5], 0 , strpos($rows[0]['data'][5] , '-' ) )  .' - ' . $rows[0]['data'][4]. '<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows[0]['data'][6].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/madison-plateau">Madison Plateau SNOTEL</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '7750&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows2[0][4] . '&#x2109;</td></tr>';

	$markup .=       '<tr><td class = "details">'. $rows2[0][2].'&#8243; <span class = "data-sub">Depth</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
	
  $markup .= gnfac_advisory_region_body($advisory, 29, 'lon=-111.30645604248043&lat=44.71433192428469', $title ,
	  "<a href = 'https://bigskyresort.com/the-mountain/webcams' target = '_blank' >Rendezvous Ski Trail Webcam</a></br>".
		"<a href = 'http://www.westyellowstonewebcams.com/' target = '_blank' >W. Yellowstone Webcams</a></br>"
	 );
	// */
	return  $markup;
}

function gnfac_advisory_cooke($title){
	$advisory = gnfac_current_advisory('node') ;
  $markup = '';	
  $transforms = array( '5' => 'gnfac_cardinal_wind_dir' );
	$precip_history = gnfac_get_history_precip('field_cooke_city_precip');

  $rows = gnfac_fetch_hobo_file( 'cooke', "300234010499280" , $transforms, TRUE );
	$rows2 = gnfac_fetch_nrcs_snotel_data('480' , TRUE);
	

	$time =   substr($rows[0][0], 0, 5 )  .' at '. substr($rows[0][1], -4 );
	$time2 =    str_replace( '-', '/' ,substr( trim($rows2[0][0] ), 5 , 5 )) . ' at ' . substr( trim($rows2[0][0] ), 10 );

	$markup .= '<div class = "weather-locations" >';	
	$markup .= '<div class = "wx-log-link"><span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></div>';

	$markup .=  gnfac_precip_history_block($precip_history);

	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href ="/weather/stations/cooke-city">Lulu Pass Weather Station</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9984&#8242; &nbsp; &nbsp; '. $time;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows[0][2] . '&#x2109;</td></tr>';
	$markup .=       '<tr><td class = "details">'. substr($rows[0][6], 0 , strpos($rows[0]['data'][6] , '-' ) )  .' - ' . $rows[0][4]. '<span class = "data-sub">mph</span></td></tr>';
	$markup .=       '<tr><td class = "details"><span class = "data-sub">Gusts</span> '. $rows[0][5].'<span class = "data-sub">mph</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "/weather/stations/fischer-creek">Fisher Creek SNOTEL</a>';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       '9100&#8242; &nbsp;  '. $time2 ;
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="details">'. $rows2[0][4] . '&#x2109;</td></tr>';

	$markup .=       '<tr><td class = "details">'. $rows2[0][2].'&#8243; <span class = "data-sub">Depth</span></td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row

	$markup .= '</div>'; // end weather-locations
	
  $markup .= gnfac_advisory_region_body($advisory, 28, 'lon=-109.91440389404296&lat=45.049904852156004' , $title ,
	  "<a href = 'http://cookecity.net/webcams/live-cams/' target = '_blank' >Soda Butte Lodge Webcams</a>");
	// */
	return  $markup;
}

function gnfac_advisory_region_body($advisory, $tid, $location , $title , $webcams = ''){
	
	$advisory_region_groups = $advisory->field_region_group_1->getValue() ;
  $bottom_line = '';
  $markup = '';
	foreach( $advisory_region_groups as $key2 => $region_group) {
	    $fc = \Drupal\field_collection\Entity\FieldCollectionItem::load($region_group['value']);
			
  	  if ( in_array( array( 'target_id' => $tid)  , $fc->field_applicable_regions->getValue() )   ){  // 
			$bottom_line = $fc->field_regional_discussion->summary;
			$options = $fc->field_problem_type->getSetting('allowed_values');
	    $problem_type = $options [ $fc->field_problem_type->value ];
	    $region_hazard = (($fc->field_regional_hazard_rating->value <> '' ) && mktime($advisory->field_valid_dates->value) > time()) 
				?  $fc->field_regional_hazard_rating->value : 'None' ;

		}
	}

	$forecasters_choice_image = Drupal\node\Entity\Node::load($advisory->field_forecasters_choice_image->target_id);
	if (isset ( $forecasters_choice_image->field_image_file )){
	  $styled_image_url = ImageStyle::load('medium')->buildUrl($forecasters_choice_image->field_image_file->entity->getFileUri());
	  $image_title = $forecasters_choice_image->title->value;
	}
	$fc_text = $advisory->field_forecasters_choice_text->value;

	$markup .= '<div class = "hazard-rating-container"><img src = "/images/hazard_ratings/'.$region_hazard.'.png" class ="regional-hazard-image" /></div>';
	$markup .= '<div class = "bottom-problem-container group">';
	
	$markup .= '<div class ="bottom-line firsty"><div class = "bottom-line-wrapper"><span class = "label">Bottom Line: </span>'. t($bottom_line) . '</div></div>';

 
	$markup .= '<div class = "problem-type secondy"><div class = "problem-type-wrapper"><span class = "label"><a href = "http://avalanche.state.co.us/forecasts/help/avalanche-problems/" target ="_blank">Primary Problem</a>: </span>'. $problem_type .'<div class = "advisory-link"><ul class = "button-list"><li><a href = "/advisory" title = "Complete Daily Avalanche Advisory for all regions of the GNFAC forecast area.">Full Advisory</a></li></ul></div></div></div>';
	$markup .= '</div>';
	 //$markup .= t('<em>Daily weather and avalanche log</em>');
	// $markup .= '<div class="view-weather-log" >';
  // $markup .= '<h3 class = "advisory sub-page">3 Day Weather and Avalanche Log <span class = "right tiny"><a href = "/weather/wx-avalanche-log">View Weather and Avalanche Log</a></span></h3>';
	// $daily_wx_view = views_embed_view('weather_log', 'block_1');
	// $markup .=  \Drupal::service('renderer')->render($daily_wx_view);
 
	// $markup .= '</div>'; // end weather logs block

	$bundle = 'advisory'; 
	  $query = \Drupal::entityQuery('node');
	    $query->condition('status', 1);
	    $query->condition('type', $bundle);
	    $query->range(0,5);
	    $query->sort('created', 'DESC');
	    $advisory_ids = $query->execute();	
			$advisory_ids = array_reverse($advisory_ids );
			$advisories_hist = Drupal\node\Entity\Node::loadMultiple($advisory_ids);
			

			$markup .= '<div class = "hazard-history"  >';
			$markup .= '<h3 class = "advisory sub-page">Past 5 Days</h3>';
			foreach ( $advisories_hist as $key => $advisory_hist ){
				$advisory_region_groups = $advisory_hist->field_region_group_1->getValue() ;
				$hist_rating[$key] = 'None'; // start with None,set to something , if it exists
	      foreach( $advisory_region_groups as $key3 => $region_group) {	
		      $fc2 = \Drupal\field_collection\Entity\FieldCollectionItem::load($region_group['value']);
		      if ( in_array( array( 'target_id' => $tid), $fc2->field_applicable_regions->getValue())   ){  // 23 is the Bridgers
						$hist_rating[$key] = !isset($fc2->field_regional_hazard_rating->value ) ? 'None' : $fc2->field_regional_hazard_rating->value; 
			
					}
				}
				$markup .= '<div class = "hazard-day"> ';
				$markup .=   ( (date( 'M', $advisory_hist->created->value )  == date('M' ) ) && ( date('j', $advisory_hist->created->value ) == date('j' ) )  )  
					? 'Today' : date ('D M j', $advisory_hist->created->value) ; $markup .= '<br />' ;
			
				$markup .= '<img src = "/images/hazard_ratings/simple/'. $hist_rating[$key]  .'.png" /><br />';
				$markup .= $hist_rating[$key];
				$markup .= '</div>';
			}
			$markup .= '</div>'; // end hazard history block
			/////////////////////////////////////////////////////////////////////////////////////////////////////////
			// Start Photos, videos, snowpits, weather stations blocks
			
			
			////////////////////////////////////////////////////////////////////////////
			$markup .= '<div class = "group media-blocks"> ';
			
			$markup .= '<div class = "two-col firsty photos" ><h3 class = "advisory sub-page"><a href = "/photos/">Photos</a>- ' . $title . '</h3>';
			$sub_advisory_photos_view=views_embed_view('photos', 'block_3', $tid);
		  $markup .=  \Drupal::service('renderer')->render($sub_advisory_photos_view);
			$markup .= '</div>';
				
			$markup .= '<div class = "two-col secondy videos" ><h3 class = "advisory sub-page"><a href ="https://www.youtube.com/playlist?list=PLXu5151nmAvQSYtIfyQP-gMYrlfja6Ls" target = "_blank">Videos</a>- ' . $title . '</h3>';
			$sub_advisory_videos_view = views_embed_view('videos_list', 'block_1', $tid);
			$videos_view_markup = \Drupal::service('renderer')->render($sub_advisory_videos_view);
			$markup .=  $videos_view_markup;
			$markup .= '</div>';	
			
			$markup .= '</div>'; // end class 'group' and media-blocks
			
			
			$markup .= '<div class="group media-blocks">';
			$markup .= '<div class = "two-col firsty snowpits" ><h3 class = "advisory sub-page"><a href ="/snowpits">Snowpit Profiles</a>- ' . $title . '</h3>';
			$sub_advisory_snowpits_view = views_embed_view('photos', 'block_2', $tid) ;
		  $markup .=  \Drupal::service('renderer')->render($sub_advisory_snowpits_view);
			$markup .= '</div>';
			
			$markup .= '<div class = "two-col secondy wx-stations" ><h3 class = "advisory sub-page"><a href ="/weather">Weather Stations</a>- ' . $title . '</h3>';
			$sub_advisory_wx_view = views_embed_view('weather_stations', 'block_1', $tid);
		  $markup .=  \Drupal::service('renderer')->render($sub_advisory_wx_view);
			
			$markup .= "<img src = '/sites/all/themes/gnfac_theme/images/cam.png' class = 'webcam-image' />".$webcams;
			$markup .= '</div>';
			
			
			
			// end first pair group
			$markup .= '</div>';
			// start new group

		

			// Weather forecast / Point forecast block  gnfac-fs
		
			
			///////////////////////////////////////////////////////////
			$markup .= '<div class = "group point-choice">';
			
			$url="https://forecast.weather.gov/MapClick.php?" . $location . "#detailed-forecast";
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, $url);
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			curl_setopt($ch,CURLOPT_USERAGENT,'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13');
			$html = curl_exec($ch);
			curl_close($ch);
		  $dom = new DOMDocument();
			@$dom->loadHTML($html);
			$dataElement = $dom->getElementById('seven-day-forecast');
		
			$xml = $dataElement->ownerDocument->saveXML($dataElement);
			$xml = (str_replace( '<img src="' , '<img src="https://forecast.weather.gov/',$xml));
		
			$markup .= '<div class = "two-col firsty point-forecast" >';
			
			$forecast_link = Link::fromTextAndUrl(t('Full Forecast, NOAA website'), Url::fromUri($url) );
			$forecast_link = $forecast_link->toRenderable();
			
			$markup .= '<h3 class = "advisory sub-page">Weather Forecast  ' . $title . '</h3>';
			$markup .= '<div class ="point-forecast noaa-link">'. render($forecast_link) . '</div>';
			
			$final_text = preg_replace( '/<script type="text\/javascript">[\s\S]*<\/script>/' , '', $xml );
			//$markup .= Xss::filterAdmin($final_text);
			$markup .= check_markup($final_text, 'basic_html');
			
			$markup .= '</div>';//this ends the 'firsty point-forecast' div
			
			// Forecaster's Choice
		
			$markup .= '<div class ="two-col secondy forecasters-choice"><h3 class = "advisory sub-page">Forecaster\'s Choice</h3>';
      if ($styled_image_url) {
				$markup .= '<div class ="forecasters-image title">'.'<img src ="'.$styled_image_url. '" /></div>';
    	}
			$markup .= '<div class = "fc-text">'.$fc_text .' </div>';
			$markup .= '</div>'; // end .forecasters choice
			$markup .= '</div>';  // end group .point-choice
		


			return  $markup;
}

function gnfac_get_history_precip($precip_field_name){
	$bundle = 'wx_log'; 
	  $query = \Drupal::entityQuery('node');
	    $query->condition('status', 1);
	    $query->condition('type', $bundle);
	    $query->range(0,3);
	    $query->sort('created', 'DESC');
	    $advisory_ids = $query->execute();	
			$advisories_hist = Drupal\node\Entity\Node::loadMultiple($advisory_ids);
			
			foreach ( $advisories_hist as $key => $advisory_hist ){
				$precip_history[]= array ('precip' => $advisory_hist->$precip_field_name->value,
				//'day' =>  $advisory_hist->id() == gnfac_current_advisory()      ? 'Today' : date( 'l' ,$advisory_hist->created->value)
				'day' =>  $advisory_hist->id() == gnfac_current_advisory()      ? 'Today' : date( 'M j' ,$advisory_hist->created->value)
				) ;				
			}
			return $precip_history;
}

function gnfac_precip_history_block($precip_history){
	$markup = '';
	$markup .=   '<div class = "views-row" >';
	$markup .=     '<div class = "views-field views-field-title" >';
	$markup .=       '<a href = "#">24 Hour Snowfall and Wind</a> ';
	$markup .=     '</div>';
	$markup .=     '<div class = "views-field views-field-wx-station-info" >';
  $markup .=       'as of 5:00 am ';
	$markup .=     '</div>';
	$markup .=     '<table class = "views-field views-field-data" >';
	$markup .=       '<tr><td class ="labels"><span class = "data-sub">'.  $precip_history[0]['day'] .  '</span></td><td class ="details left">'. $precip_history[0]['precip'] . '</td></tr>';
	$markup .=       '<tr><td class ="labels"><span class = "data-sub">'.  $precip_history[1]['day'] . ' </span></td><td class = "details left">'. $precip_history[1]['precip']. '</td></tr>';
	$markup .=       '<tr><td class ="labels"><span class = "data-sub">'. $precip_history[2]['day'] . ' </span></td><td class = "details left">'. $precip_history[2]['precip'].' </td></tr>';
	$markup .=     '</table>'; // end views-field-data
	$markup .=   '</div>'; // end views-row
	
	return $markup;
}