<?php

use Drupal\node\Entity\Node;
use Drupal\Component\Utility\Unicode;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Controller\ControllerBase;
use Drupal\field_collection\Entity\FieldCollectionItem;

use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;

use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\image\Entity\ImageStyle;
use Drupal\file\Entity\File;

function gnfac_d8_form_alter(array &$form, FormStateInterface &$form_state, $form_id){
	///////////
	if ( isset($form['field_latitude']) ){
		$form['field-google-map'] = array( '#type' => 'markup', '#markup'=> '<div id="google-map"></div>' , '#weight' => 3);
		$form['#attached']['library'][] = 'gnfac_d8/gnfac-geographic';
	}
	
	if ( isset($form['field_regions_similar']) ){
		$form['#attached']['library'][] = 'gnfac_d8/gnfac-forms';
		
		
	}
	switch ( $form_id){
		case 'node_advisory_form':
		// copy yesterdays last word to todays, as a default: https://github.com/jimurl/gnfac-d6-d8/issues/265
		$current = gnfac_current_advisory('node');
		$form['field_forecasters_choice_text']['widget'][0]['#default_value'] = $current->field_forecasters_choice_text->value;
		
		case 'node_advisory_edit_form':
		foreach ( $form['field_region_group_1']['widget'] as $key => $region_group ){
		  if ( is_numeric($key)){
		    $form['field_region_group_1']['widget'][$key]['field_regional_discussion']['widget'][0]['summary']['#title'] = "Bottom Line ( used on the region conditions pages )";
		    $form['field_region_group_1']['widget'][$key]['field_regional_discussion']['widget'][0]['summary']['#description'] = 'Used on the region conditions pages.';
			  $form['field_region_group_1']['widget'][$key]['field_regional_discussion']['widget'][0]['summary']['#weight'] = '1' ;
			  foreach ( $region_group['field_applicable_regions']['widget']['#default_value'] as $region ){
						// If a region has been chosen in one of the previous field collection items, don't display the checkbox as an 'applicable Region' in the newest region group
					foreach ( $form['field_region_group_1']['widget'] as $key2 => $region_group2 ){
						if ( ($key2 <> $key) && is_numeric($key2)){
							unset($form['field_region_group_1']['widget'][$key2]['field_applicable_regions']['widget']['#options'][$region]);
						}						
					}
				}		
			}
	  }		
    foreach (array_keys($form['actions']) as $action) {
       if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
           $form['actions'][$action]['#submit'][] = 'gnfac_d8_advisory_form_submit';
       }
    }
				break;
		case 'node_snow_observation_form':
      foreach (array_keys($form['actions']) as $action) {
         if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
             $form['actions'][$action]['#submit'][] = 'gnfac_d8_snow_obs_form_submit';
         }
      }
			//kint($form);
		break;
		case 'node_page_edit_form':
    $node = \Drupal::routeMatch()->getParameter('node');
		//kint($node);
		if ($node->nid->value == '12087' ){ // this is the NWS Avalanche Warning page , /data/noaa.txt
      foreach (array_keys($form['actions']) as $action) {
         if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
					 $form['actions'][$action]['#submit'][] = 'gnfac_d8_write_noaa_warning_file';
         }
      }
      $form['field_file_upload']['#access'] = FALSE;
			$form['title']['widget'][0]['value']['#default_value'] = "ISSUED ON ".date('F d Y')." AT ".date('h:i a');
	  }
		
		break;
		case 'node_blog_edit_form':
    $node = \Drupal::routeMatch()->getParameter('node');
		if ($node->nid->value == '17736'){  // this is the Non-Advisory email page: /email/non-advisory
      $form['field_file_upload']['#access'] = FALSE;
		}
		break;
		case 'node_image_edit_form':
		case 'node_image_form':
		  $form['body']['widget'][0]['#format'] = 'basic_html';
		break;
		
		//  
		//
		case 'views_exposed_form':
		if ( isset($form['field_advisory_year_target_id']) && $form['field_advisory_year_target_id']['#default_value'] == 'All'){
			foreach ( $form['field_advisory_year_target_id']['#options'] as $key => $option ){
				if ( $key > gnfac_current_year() ) unset( $form['field_advisory_year_target_id']['#options'][$key]);
			}
		}		
		break;
		case 'node_wx_log_form':
		  //dsm($form['field_bridgers_weather_station']);
			$form['#attached']['library'][] = 'gnfac_d8/gnfac-wx-log';
			
			$form['#attached']['drupalSettings']['gnfac_d8']['gnfac_weather']['bridgers_swe'] = '12.3';
			$all_regions = array( 'bridgers', 'n_madison', 's_madison', 'lionhead', 'cooke', 'n_gallatin', 's_gallatin' );
			
			foreach( $all_regions as $region ){
				
				// $key is from the gui admin node type configs: field_bridgers_weather_station - it needs to be the nid of the weather station
				foreach($form['field_'. $region .'_weather_station']['widget']['#options'] as $key => $option_label ){
					$station = Drupal\node\Entity\Node::load($key);
					$station_latest_data = $station->field_recent_wx_data->value; 
					dsm($station_latest_data);
					preg_match( '/<td>\s*Date<\/td><td>([\s\d\w:-]*)<\/td>/', $station_latest_data ,$matches); // this will need to become fancier to accomodate all the different date/ time formats
					dsm($matches);
					if ( $matches ){
					  $form['field_'. $region .'_weather_station']['widget']['#options'][$key] = 
						$form['field_'. $region .'_weather_station']['widget']['#options'][$key] . $matches[1];
					}	
					$form['#attached']['drupalSettings']['gnfac_d8']['gnfac_weather'][$region]['_'.$key]['swe'] = '45.6';
					
				}
			}
			
		
			//dsm($form['field_bridgers_weather_station']['widget']['#options']);
		break;
			
	}	
  if ( isset($form['field_advisory_year']) ){

		if ( ! $form['field_advisory_year']['widget']['#default_value']  ){
			$form['field_advisory_year']['widget']['#default_value'] = gnfac_current_year(); 
		}
		
  } 
	return $form;
}

function gnfac_display_video($vid_string = NULL , $format = 'default'){
	switch ( $format){  
		case 'image':
		case 'large':
		  $width = '420px';
		  $height = ' 338px';
		break;
		case 'medium':
	    $width = '330px';
	    $height = ' 266px';
			break;
		default:
	    $width = '100%' ;
	    $height = 'auto';
		break;
  }
	$output = "";
  if ($vid_string && $format <> 'image') {
		$output .=  '<div class="gnfac_attached_video" >';
		$output .= '<object data="https://www.youtube.com/embed'. $vid_string . '" width="' . $width . '" height="' . $height . '"></object>';
		$output .= '</div>';
  }elseif( $vid_string){
  	$output .= '<div class ="gnfac_attached_vid_image" style = "max-width: 300px;">
			<a href = "https://www.youtube.com/watch?v='. substr($vid_string, 1 ) . '" target = "_blank">
			<img src = "https://i.ytimg.com/vi'. $vid_string . '/0.jpg"  width ="275px" />
			</a></div>';
		
		
  }
	return $output;

}

/**
 *   Mail snow obs results
 */
function gnfac_d8_snow_obs_form_submit($form, $form_state){
	gnfac_d8_extracted_mailer($form, $form_state);
	return;
}

function gnfac_d8_advisory_form_submit($form, $form_state){
	// advisory caaml build
	
	// Only update advisory caaml if this is the current advisory
/*	if ( gnfac_current_advisory('nid') == $form_state->getValue('nid') ){
	  advisory_caaml_build_xml();
  	advisory_caaml_push_xml();
	}
	
	require_once DRUPAL_ROOT.'/libraries/avalanche.org-API-Client/AvalancheAPI.php';
  $api = new AvalancheAPI();
  $result = $api->updateForecast('GNFAC');			
			*/
	include_once( DRUPAL_ROOT.'/'.drupal_get_path('module', 'gnfac_d8').'/inc/advisory-map.inc.php');
	gnfac_generate_advisory_map( gnfac_current_advisory('nid'), 'web', TRUE );
	
	return;
}

function gnfac_d8_write_noaa_warning_file($form, $form_state){
	//$pre_body = $form_state->getValue('body');
	$title = $form_state->getValue('title');
	$title_text = $title[0]['value'];
	
	$body = $form_state->getValue('body');
	$body_text = $body[0]['value'];
	
	$noaa_data_file = fopen(DRUPAL_ROOT.'/data/noaa.txt', 'w');
	fwrite ($noaa_data_file, $title_text . '
'.$body_text );
	fclose($noaa_data_file);
	return;
	
}

function gnfac_d8_extracted_mailer($form,$form_state){
	  //\Drupal::logger('gnfac_d8')->info();
		$name = $form_state->getValue('field_name');
		$full_name = $name[0]['value'];
	  $to = 'mtavalanche@gmail.com,jimurl@mtavalanche.com';
	  $subject = 'New Snow Obs from: '.$full_name;
	  $message = 'New Snow Observation from: '.$full_name. "\r\n";
		
		$pre_body = $form_state->getValue('body');
		$pre_replyto = $form_state->getValue('field_email');
    $pre_activity = $form_state->getValue('field_activity');
		$pre_city = $form_state->getValue('field_citystatezip');
		$pre_date = $form_state->getValue('field_date');
		$pre_location = $form_state->getValue('field_location');
		$pre_lat = $form_state->getValue('field_latitude');
		$pre_long = $form_state->getValue('field_longitude');
		$pre_phone = $form_state->getValue('field_phone');
		
		$message .= '<b>Activity:</b> '. $pre_activity[0]['value']. "\r\n";
		$message .= '<b>City,State,Zip:</b> '. $pre_city[0]['value']. "\r\n";
		$message .= '<b>Date:</b> '. $pre_date[0]['value']. "\r\n";
		$message .= '<b>Location:</b> '. $pre_location[0]['value']. "\r\n";
		$message .= '<b>Latitude:</b> '. $pre_lat[0]['value']. "\r\n";
		$message .= '<b>Longitue:</b> '. $pre_long[0]['value']. "\r\n";
		$attachments = '';
		
		$message .= '<b>Snow Observations:</b> ' . $pre_body[0]['value']. "\r\n";
		$replyto = $pre_replyto[0]['value'] ? $pre_replyto[0]['value'] : 'advisory@mtavalanche.com';
	
		// Attach the attachments!
		$attached_files = $form_state->getValue('field_file_upload') ;
		$random_hash = md5(date('r', time())); 
		
		foreach ($attached_files as $attached_file ){
			if ( $attached_file['fids']){
        $file = \Drupal\file\Entity\File::load($attached_file['fids'][0]);
        $file_relpath = $file->getFileUri() ;
				$message .= file_create_url($file_relpath) . "\r\n";
				$attachments .= "--PHP-mixed-".$random_hash. "\r\n"; 
				$attachments .= "Content-Type: " .$file->getMimeType() . "; name=".$file->getFilename(). "\r\n";
        $attachments .= "Content-Transfer-Encoding: base64". "\r\n";
        $attachments .= "Content-Disposition: attachment"."\r\n";
        $attachments .= "filename = ".$file->getFilename(). "\r\n";
				$attachments .= chunk_split(base64_encode(file_get_contents(DRUPAL_ROOT.'/sites/default/files/'.str_replace( 'public://', '' ,$file_relpath ) )));
			}
		}


	//create a boundary string. It must be unique
	//so we use the MD5 algorithm to generate a random hash
	//add boundary string and mime type specification


	  $additional_headers = 'From: mtavalanche@gmail.com'. "\r\n";
		$additional_headers .= 'Reply-To: '.$replyto. "\r\n";
		$additional_headers .= "MIME-Version: 1.0" . "\r\n";
	$additional_headers .= "Content-Type: multipart/mixed;
	 boundary=\"PHP-mixed-".$random_hash."\"". "\r\n"; //boundary=PHP-mixed-".$random_hash;

	ob_start(); //Turn on output buffering
	?>
--PHP-mixed-<?php echo $random_hash. "\r\n"; ?>
Content-Type: multipart/alternative; boundary="PHP-alt-<?php echo $random_hash; ?>" 

--PHP-alt-<?php echo $random_hash. "\r\n"; ?>
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 7bit

<?php echo $message; ?>

--PHP-alt-<?php echo $random_hash. "\r\n"; ?>
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: 7bit
<html><body>
<?php 
echo check_markup($message, 'restricted_html'); 
?>
</body>
</html>
--PHP-alt-<?php echo $random_hash; ?>--

<?php echo $attachments; ?>
--PHP-mixed-<?php echo $random_hash; ?>--

<?
	//copy current buffer contents into $message variable and delete current output buffer
	$final_message = ob_get_clean();
	  $result = mail (  $to ,  $subject ,  $final_message ,  $additional_headers  );
	   //echo ("Mail was sent? ". $result);

	
}

// 
function gnfac_video_extract_string($video_url){
  $video_url_final = ( strpos($video_url , 'watch?v=' )  ) ? '/'.substr( $video_url , strpos($video_url , 'watch?v=' )+8 ) : $video_url;	
  $video_url_final2 = strpos($video_url_final, '&') ? substr($video_url_final , 0, strpos($video_url_final, '&')) : $video_url_final;
  $video_url_final3 = (strpos($video_url_final2, 'https://youtu.be/') === 0) ? substr( $video_url_final2 , 16 ) : $video_url_final2 ;
  $video_url_final4 = (strpos($video_url_final3, 'http://youtu.be/') === 0) ? substr( $video_url_final3 , 15 ) : $video_url_final3 ;
	
	return $video_url_final4 ;
}


function gnfac_current_advisory($format='nid'){
	$current_advisory_sql = "SELECT n.nid FROM node as n 
		join `node_field_data` as nfd on (n.nid=nfd.nid AND n.vid=nfd.vid) 
	  WHERE nfd.status = 1 and n.type = 'advisory' 
		ORDER BY created DESC LIMIT 1 ";
		$results = db_query($current_advisory_sql);
		
		foreach( $results as $result){
		$node = Drupal\node\Entity\Node::load($result->nid);
		$nid = $result->nid;
	}
	if ( $format == 'node'){
		return $node;
	}else{
		return $nid;
	}
}

/**
 * Implements hook_field_extra_fields().
 */
function gnfac_d8_entity_extra_field_info() {
  // Put the content type you want to display summary field here.
  $extra['node']['advisory']['display']['body_summary'] = array(
    'label' => t('Body summary'),
    'description' => t('Display body summary.'),
		'weight' => 0,
  );
	$extra['node']['image']['display']['image_sizes_links'] = array(
		'label' => t('Other Image sizes'),
		'description' => t('Image Sizes'),
		'weight' => 0,		
	);
	$extra['node']['weather_station']['display']['wx_data_table'] = array(
		'label' => t('Wx Data Table'),
		'description' => t('Rendered table showing current weather for this site.'),
		'weight' => 0,		
	);
	//dsm($extra);
  return $extra;
}

function gnfac_d8_field_collection_item_view_alter(&$build, $entity, $display) {

}

function gnfac_d8_page_attachments(array &$attachments) {
	
  $attachments['#attached']['library'][] = 'gnfac_d8/gnfac-libraries';
	//
	//  Geographic scripts should only be loaded on pages that need them:
  // images nodes, videos, snowobs, accident, placename, weather station
	//
	// Also on these pages: placenames map , weather map page
	// later maybe some weather stationparent pages, like 'Bridger' or 'Big sky'
	$node = \Drupal::routeMatch()->getParameter('node');
	if ( in_array($node->type->target_id,array ('weather_station', 'accident', 'image', 'video', 'place_name', 'snow_observation'))
	  || (\Drupal::routeMatch()->getRouteName() == 'node.add')    ){	
		$attachments['#attached']['library'][] = 'gnfac_d8/gnfac-geographic';
  }
	
	return $attachments;
}



/**
 * Implements hook_node_view().
 */

function gnfac_d8_node_view_alter(&$build, $entity, $display ) {
  // Put the content type you want to display summary field here.
  $display_id = $display->id() ;

	if ($display->getComponent('body_summary')) {
		//kint ( $entity->get('field_region_group_1'));
	  //kint ($region_groups);
		$region_groups = array();
		$fc_ids = array();
		$submit_obs_button = ( $display_id == 'node.advisory.pdf' ) ? '' : '<div><ul class = "button-list"><li><a href ="/node/add/snow_observation">Submit Snow Observations</a></li></ul></div>'.'</div>';
    $markup = gnfac_d8_compile_regions($entity, $display_id); // display_id is either node.advisory.pdf or node.advisory.default

      $build['_field_layout']['content']['body_summary'] = [
        '#type' => 'markup',
				'#prefix' => '<div class ="discussion"><div class = "field__label">Snowpack and Avalanche Discussion</div>',
				'#suffix' => $submit_obs_button,
        '#children' => $markup, 
				'#weight' => 2,
      ];
		
	}
	if ( $display-> getComponent('field_weather') && $display_id <> 'node.advisory.pdf' ){
		$full_weather_link = '<div class = "full-weather-wrapper "><ul class = "full-weather button-list"><li class= "full-weather-item"><a href = "/weather/wx-avalanche-log">Weather and Avalanche Log</a></li></ul></div> ';
		$build['_field_layout']['content']['field_weather'][0]['#text'] = $build['_field_layout']['content']['field_weather'][0]['#text'] .$full_weather_link;
	}
	
	if ( $display->getComponent('image_sizes_links') && isset ($entity->field_image_file->target_id)) {

		$sizes = array( 'very_large_1200w_' => 'Very Large 1200px', 'large' => 'Large 480px', 'medium' => 'Medium 220px', 'small_plus_150' => 'Small 150px');

		$build['field_layout']['content']['image_sizes_links'] = [
			'#type' => 'markup',
			'#prefix' => '<div class ="sizes-links">Access other image sizes:',
			'#suffix' => '</div>',
			'#children' => 	gnfac_images_sizes_build($sizes, $entity->field_image_file->target_id ),
			'#weight' => 5,			
		];
		
	}
	if ( $entity->nid->value == '17736') {   // Non advisory email, output on /email/non-advisory
		$build['_field_layout']['content']['body'] = [
			'#type' => 'markup',
			'#children' => gnfac_style_h3($build['_field_layout']['content']['body'][0]['#text']),
			'#prefix' => '<div class ="non-advisory-body">',
			'#suffix' => '</div>',
		];
	}
	
	if ( $entity->nid->value == '12061'  || $entity->nid->value == '18913') {   // /weather page  , test weather page:  || $entity->nid->value == '18913'
		$build['#cache']['max-age'] = 0; 
		 \Drupal::service('page_cache_kill_switch')->trigger();
	}
	
	if ( $entity->type->target_id =='weather_station' ){
		switch ( $entity->field_weather_station_type->target_id ){
			case '434':
		    $markup = gnfac_fetch_nrcs_snotel_data( $entity->field_nrcs_snotel_site->value );
			break;
			case '436':
			  $markup = gnfac_fetch_rpt_file( $entity->field_rpt_path->value , 'lookup');
			break;
			case '435':
			if ( isset($entity->field_data_garrison_id->value )){
			  $markup = gnfac_fetch_hobo_file( $entity->field_data_garrison_id->value );
			}elseif ( $entity->field_rpt_path->value ){   /// This one stupid exception is for the Lionhead weather station
			   $markup = gnfac_fetch_rpt_file( $entity->field_rpt_path->value , 'lookup');  // even though it is GNFAC -owned, the data comes via rpt file, like ski areas
			}
			break;
		}
		$age =  (\Drupal::currentUser()->isAnonymous()) ? 3*60 : 0  ; // 3 minutes for anonymous users, 0 for logged in
		$build['field_layout']['content']['wx_data_table'] = array(
			'#type' => 'markup',
			'#prefix' => '<div class ="wx-data-table">',
			'#suffix' => '</div>',
			'#children' => 	$markup,
			'#weight' => 5,			
			'#cache' => array( 'max-age' => $age ),
		);
	}

}

function gnfac_d8_link_alter(&$variables) {
  if ($variables['url']->isExternal()) {
    $variables['options']['attributes'] = ['target' => '_blank'];
  }
}

function gnfac_images_sizes_build($sizes, $entity_id ){
	$image_file = File::load( $entity_id );
	$markup ='';
  $url = $image_file->getFileUri();

	foreach ( $sizes as $key => $size ){
	  $styled_image_url = ImageStyle::load($key)->buildUrl($image_file->getFileUri());
		
		$linked = Link::fromTextAndUrl( t( $size ), Url::fromUri( $styled_image_url ) );
		$linked = $linked->toRenderable();
		$markup .= '<li>'. render($linked) . '</li>';    
	}
	$link_Original = Link::fromTextAndUrl( t( 'Original'), Url::fromUri( 'https://www.mtavalanche.com/sites/default/files/'. substr($url, strpos($url, '://') + 3 ) ) );
	$link_Original = $link_Original->toRenderable();
	
	$markup .= '<li>'. render($link_Original) . '</li>';  
	return $markup;
}
//
// $format can be $display_id values of 'node.advisory.default' or 'n.a.pdf' , or  'email' , depending on if the styles will also be written inline
//


function gnfac_d8_compile_regions($entity, $display_id = 'node.advisory.default'){ // $display_id will generally be 
	$markup = '';
	
	foreach ($entity->get('field_region_group_1') as $key => $region ){
		//kint($region);
    $fc_ids[$key] = $region->getValue()	;		
		$fc = FieldCollectionItem::load($fc_ids[$key]['value']);
		$fc_regions = $fc->field_applicable_regions->getValue();
		$fc_details = $fc->field_regional_discussion->getValue() ; 
		$fc_hazard = $fc->field_regional_hazard_rating->value;
		$fc_warning = $fc->field_avalanche_warning->value ? ' warning' : '' ;
		
		
		switch ( $display_id ){
		  case 'node.advisory.default':
			  $markup .= '<div class = "region-group'. $fc_warning.'" > ';
				$fc_haz_image =   !$fc_hazard ? '' :  $fc_haz_image = '<div class = "region hazard-rating-image" ><a href ="#" title = "'. $fc_hazard .' Avalanche Hazard" alt ="'. $fc_hazard .' Avalanche Hazard"><img src ="/images/hazard_ratings/simple/' .  $fc_hazard .'.png" class = "hazard-image-main"   /></a><br /></div>';
				$markup .=  $fc_haz_image. '<h3 class ="region"  >' . implode ( '</h3><h3 class ="region" >' , gnfac_region_groups_header_markup($fc_regions, 'links') ) .'</h3>';
				$markup .= '</div>';	
				if ( $fc_warning == ' warning' ){ $markup .= '<h3 class = "warning" >Avalanche Warning</h3>';}
				$render_format = $fc_details[0]['format'];
			break;
			case 'node.advisory.pdf':
		    $markup .= '<table class = "region-group'. $fc_warning .'" ><tr> ';
			  $fc_haz_image =   !$fc_hazard ? '' :  '<td class = "region hazard-rating-image"  style = "width: 35px;" ><img src ="/images/hazard_ratings/simple/' .  $fc_hazard .'.png" class = "hazard-image-main"  style = "height: 32px; padding-left: 4px;"   /></td>';
				$markup .=  $fc_haz_image. '<td class ="region"  style = "margin: 0;	vertical-align: top; padding: 5px 7px; font-size: 15pt; color: #162f50;"  >';
				$markup .= implode ( '</td><td class ="region"  style = "margin: 0;	vertical-align: top; padding: 5px 7px; font-size: 15pt; color: #162f50; " >' , gnfac_region_groups_header_markup($fc_regions, 'nolinks') ) .'</td>';
				$markup .= '</tr ></table>';
				if ( $fc_warning == ' warning' ){ $markup .= '<h3 class = "warning" style = "" >Avalanche Warning</h3>';}
				$render_format = 'basic_html';

			break;
			case 'email':
			  $markup .= '<table class = "region-group"  style = "background-color: #617490; margin-top: 0px; border-top: 4px solid #162f50; color: #fafafa; width: 100%; font-family: Arial, sans-serif; height: 45px;"  ><tr> ';
			  $fc_haz_image =   !$fc_hazard ? '' :	$fc_haz_image = '<td class = "region hazard-rating-image"  style = "display:inline-block; width: 45px;" ><img src ="/images/hazard_ratings/simple/' .  $fc_hazard .'.png" class = "hazard-image-main"  style = "height: 32px; padding-left: 4px;"  height = "32px"   /></td>';
				$markup .=  $fc_haz_image. '<td class ="region"  style = "display: inline-block;	margin: 0;	vertical-align: top; padding: 5px 7px; color: #fff; background-color: #617490;"  >';
				$markup .= implode ( '</td><td class ="region"  style = "display: inline-block;	margin: 0;	vertical-align: top; padding: 5px 7px; color: #fff; background-color: #617490;" >' , gnfac_region_groups_header_markup($fc_regions, 'links') ) .'</td>';
				$markup .= '</tr ></table>';
				if ( $fc_warning == ' warning' ){ $markup .= '<h3 class = "warning" style = "" >Avalanche Warning</h3>';}
				$render_format = 'basic_html';
				
			break;		
		} 
	  $text_content = [
	    '#type' => 'processed_text',
	    '#text' => $fc_details[0]['value'],
	    '#format' => $render_format,
	  ];
	  $markup .= \Drupal::service('renderer')->renderPlain($text_content);
	
	}
	return $markup;
}

function gnfac_style_h3($string){
	$result = preg_replace('/([.\n\r]*)<h3>([.\n\r]*)/', '$1<h3 style = "background-color: #617490;
	    color: #fafafa;
	    padding-left: 5px;
	    padding: 3px 6px;
	    border-top: 5px solid #162f50;
			margin-bottom:0;
			margin-top: 1rem;
			font-weight: lighter;
			font-size: 1.1 rem;
			text-align: left;" >$2', $string );
	return $result;
}

/**
 * Implements hook_preprocess_HOOK() for block.html.twig.
 */

function gnfac_theme_preprocess_block(&$vars) {	
	if ($vars['derivative_plugin_id'] == 'bd1e96c9-578c-48c6-a1ba-651f2983766f'){// this is the uuid of block 21, the Weather Stations Map - JS block, which has js for the google map
		//dsm($vars['derivative_plugin_id']);
		$vars['#cache']['max-age']=0;
	}
  if ($vars['derivative_plugin_id'] == '1c0c3c56-b77c-43f1-ac8f-f15df54c3376' )  /* // this is the uuid of the 'Map View' block */
	{ 
 		  $vars['#cache']['contexts'] = ['url'];
  }
	
	if ($vars['derivative_plugin_id'] == '795132e8-5881-4429-80b0-4e23ca037aac' ) { //  'Advisory select' block - a JS chooser 
		$vars['#cache']['contexts'] = ['url'];
		$vars['#cache']['max-age'] = 20; // the advisory select block would change every day, as advisories are added
  }
	if ( $vars['derivative_plugin_id']  == '5a3af63c-d50f-4eb3-b89e-1e9c3ae414d8'  ||  // uuid of the static advisory hazard map 
    $vars['derivative_plugin_id'] == 'bd1e96c9-578c-48c6-a1ba-651f2983766f' ||
	  ($vars['derivative_plugin_id'] == 'bd1e96c9-578c-48c6-a1ba-651f2983766f')  ){ /* this is the uuid of the social media icon lins block, incl printer link*/
		$vars['#cache']['max-age'] = 0;
		
	}
	if ( $vars['plugin_id']  == 'gnfac_weather' ){  // id of the weather blocks
		$vars['#cache']['max-age'] = 0;
		$vars['#cache']['contexts'][] = 'url';
	}
	
	return $vars;
}


function gnfac_region_groups_header_markup($region_group, $links= 'nolinks'){
	$terms = \Drupal::entityManager()->getStorage('taxonomy_term')->loadTree('advisory_region');
	$region_names = array();
	foreach ($terms as $term) {
		$region_names[$term->tid] = $term->name ;
	}
	
	foreach($region_group as $region ){
	  $group[$region['target_id']] = $region_names[$region['target_id']];
	}
	$markup = array();
	
	/// all Regions
	if (count ($group) == 7) {
		$markup[] = "All Regions";
		foreach( $group as $key => $region){
			unset ($group[$key]);
		}
	}
	
	// Doing the Bridgers first, seperate, to keep everything in order
	
	if( isset($group) && in_array( 23, array_keys($group))  ){
		$link_url = Url::fromUri( 'internal:/advisory/bridgers' );
		$link_options = array ( 'attributes' => array( 'class' => array('advisory-region') , 'style' => 'color: #fafafa;') );
		$link_url->setOptions($link_options);	
		$linked_region = Link::fromTextAndUrl( t('Bridger Range'), $link_url );
		$linked_region = $linked_region->toRenderable();
		$markup[] = ($links == 'links') ?     render($linked_region) : check_markup( t('Bridger Range') ) ;  
		unset( $group[23]);
	}
	
	/// Now both gallatin ranges
	if( in_array (25 , array_keys($group)) && in_array( 27, array_keys($group))  ){
		$link_url = Url::fromUri( 'internal:/advisory/northern-gallatin' ) ;
		$link_options = array ( 'attributes' => array( 'class' => array('advisory-region') , 'style' => 'color: #fafafa;') );
		$link_url->setOptions($link_options);	
		
		$linked_region = Link::fromTextAndUrl( t('Gallatin Range'), $link_url);
		$linked_region = $linked_region->toRenderable();
		$markup[] = ($links == 'links') ?  render($linked_region) : check_markup( t('Gallatin Range') );  
		unset( $group[25]); unset ( $group[27]); 
	}
	
	
	/// Now checking if both Madison ranges ( N and S ) are in this group
	if( isset($group) && in_array (26 , array_keys($group)) && in_array( 24, array_keys($group))  ){
		$link_url = Url::fromUri( 'internal:/advisory/northern-madison' );
		$link_options = array ( 'attributes' => array( 'class' => array('advisory-region') , 'style' => 'color: #fafafa;') );
		$link_url->setOptions($link_options);	
		$linked_region = Link::fromTextAndUrl( t('Madison Range'), $link_url );
		$linked_region = $linked_region->toRenderable();
		$markup[] = ($links == 'links') ? render($linked_region) : check_markup( t('Madison Range') );  
		unset( $group[26]); unset ( $group[24]); 
	}

	foreach( $group as $region){
		$link_url = Url::fromUri( 'internal:'.gnfac_region_links($region) );
		$link_options = array ( 'attributes' => array( 'class' => array('advisory-region') , 'style' => 'color: #fafafa;') );
		$link_url->setOptions($link_options);
		$linked_region = Link::fromTextAndUrl( t($region), $link_url );
		$linked_region = $linked_region->toRenderable();
		$markup[] = ($links == 'links') ? render($linked_region) : check_markup( $region );  
	}
	
	
	return $markup;
	
}

function gnfac_region_links($region){
	switch($region){
		case 'Bridger Range':
		  $url = '/advisory/bridgers';
		break;
		case 'Northern Gallatin':
		  $url = '/advisory/northern-gallatin';
		break;
		case 'Southern Gallatin':
  		$url = '/advisory/southern-gallatin';
		break;	
		case 'Liohead Range':
		  $url = '/advisory/lionhead';
		break;
		case 'Southern Madison':
			$url = '/advisory/southern-madison';
		break;
		case 'Northern Madison':
		  $url = '/advisory/northern-madison';  
		break;
		case 'Cooke City':
		  $url = '/advisory/cooke-city';
		break;
		default:
		  $url = '/advisory/bridgers';
	}
	
	return $url;
}

function gnfac_save_recent_wx_data( $header, $rows ){
	$recent_string = '<table>';
	foreach( $rows[0] as $key => $field ){
		$recent_string .= '<tr><td>'. $header[$key] .'</td><td> '. $field .'</td></tr>';
	}
	$recent_string .= '</table>';
	return $recent_string;
}

function gnfac_fetch_nrcs_snotel_data($snotel_id = NULL,$data_only = FALSE){
	$node = \Drupal::routeMatch()->getParameter('node');
	if ( !$snotel_id ){
    
    $snotel_id =  $node->field_nrcs_snotel_site->value;
  }
	$url = 'https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport/hourly/'. $snotel_id .':MT:SNTL|id=%22%22|name/-167,0/WTEQ::value,SNWD::value,PREC::value,TOBS::value';

	$Data = file_get_contents($url);
	$tblrows = explode("\n", $Data);

	$header_trigger = FALSE; $count = 0;
	foreach ($tblrows as $tbldatas){
	  if ((substr( $tbldatas , 0 , 1 ) <> '#') && !strpos( $tbldatas, '-------' )){
	    if ( !$header_trigger ){ $header = explode (',' , $tbldatas); $header_trigger = TRUE; 
	  	}elseif ($tbldatas != NULL){
	  		$tbldata = explode( ',' , $tbldatas );
		  	$tbldata[0] = date('Y-m-j G:i', strtotime($tbldata[0] )+60*60*1 ); // Adds one hour, unless it's DST
	  	  $rows[] = $tbldata;
	    }
	  }else{ // figure out the header items, station name and elev
	    switch ($count){
	      case '0':
	        $station_name = substr( $tbldatas , 2 );
	      case '1':
	        $station_elev = substr( $tbldatas , 2); 
	    }
	    $count ++;
	  }
	}
	if (count($rows > 50)) $rows = array_slice($rows, -50); 
	
	$rows = array_reverse($rows);
  \Drupal::logger('gnfac_d8')->info('query to NRCS was made, SNOTEL#: '.$snotel_id);
	$node->field_recent_wx_data = gnfac_save_recent_wx_data( $header, $rows);
	$node->save();
  
	if ( !$data_only ){
		
	  $attributes['id'] = 'nrcstabdata';
	  $markup = '<a href ="#nrcstblbottom">Jump to table bottom</a>'; 
		  $variables = array( '#type' => 'table',
		    '#header' => $header,
	      '#rows' => $rows,
	      '#attributes' => $attributes,
			  '#sticky' => TRUE,
	    );
		$markup .= drupal_render( $variables );
	  $markup .=  "<div class = 'nrcstblbottom'><a href ='#' name = 'nrcstblbottom'></a></div>";
		return $markup;
  }else{
		return $rows;
	}
}



function gnfac_fetch_hobo_file($station, $path = NULL, $transforms = NULL , $data_only = FALSE){
  $node = \Drupal::routeMatch()->getParameter('node');
	
	if ( !$path ){
		 $path = $node->field_data_garrison_id->value;
	}
	$Data = file_get_contents('https://datagarrison.com/users/300034012539980/'. $path  .'/temp/'.$path.'_live.txt');
	$tblrows = explode("\n", $Data);
  \Drupal::logger('gnfac_d8')->info('Query to DataGarrison was made, L#: '.$path);

	$header = array('Date', 'Time',t('Temperature<br/> deg F') , 'RH, %', 'Wind Speed', 'Wind Gust' , 'Wind Direction');
	$rows = array();
	$count = 0;
	foreach ($tblrows as $tblrow){
	  $data_row_array = preg_split('/[\s]+/', $tblrow );
		if ($count >= 3 && $data_row_array[1] != '' && !preg_match( '/^[a-zA-Z]/', $tblrow )){
			$data_row[0] =$data_row_array[0];
			if ($path == '300234010341360' ){ // Lionhead WS 
				$data_row[1] = substr($data_row_array[1],0,5 );
				$data_row[2] = number_format($data_row_array[5], 1 );
				$data_row[3] = number_format($data_row_array[6], 0 );
				$data_row[4] = number_format($data_row_array[2], 0 );
				$data_row[5] = number_format($data_row_array[3], 0 );
				$data_row[6] = gnfac_cardinal_wind_dir($data_row_array[4]);
				
			}else{
			  $data_row[1] = substr($data_row_array[1],0,5 );
			  $data_row[2] = number_format($data_row_array[2], 1 );
			  $data_row[3] = number_format($data_row_array[3], 0 );
			  $data_row[4] = number_format($data_row_array[4], 0 );
			  $data_row[5] = number_format($data_row_array[5], 0 );
			  $data_row[6] = gnfac_cardinal_wind_dir($data_row_array[6]);
		 }
			$rows[] = $data_row;
		  //var_dump($data_row_array);
			
		}
		$count++;
	}
	
	if (count($rows > 50)) $rows = array_slice($rows, -50); 
  $rows = array_reverse($rows);
	$attributes['id'] = 'skiarea_tabdata';
	
	$node->field_recent_wx_data = gnfac_save_recent_wx_data( $header, $rows);
	$node->save();
	
	$markup = '';
	if ( $data_only == FALSE ){
	  $markup .= '<a href ="#nrcstblbottom">Jump to table bottom</a> '; 
		
	  $variables = array( 
			'#type' => 'table',
	    '#header' => $header,
      '#rows' => $rows,
	    '#attributes' => $attributes,
		  '#sticky' => TRUE,
    );
	  $markup .= drupal_render( $variables );
	  //print_r( theme( 'table', array( 'header' => $header, 'rows' => $rows, 'attributes'=> $attributes )) );
    $markup .= '<a name ="nrcstblbottom" class ="nrcstblbottom" href = "https://datagarrison.com/users/300034012539980/'. $path  .'/temp/'.$path.'_live.txt" >https://datagarrison.com/users/300034012539980/'. $path  .'/temp/'.$path.'_live.txt</a>';
		return $markup;
	}else{
		return $rows;
	}
}

/*
//  function gnfac_fetch_rpt_file
		params: 
			$path - string, a full local path, or a publicly accessible http:// url where the RPT file lies

			$offsets - a array in which the keys are the column numbers and the
				 values column number  at the end of x column. 

			$transforms - an array of transformations to take on the raw data. the key is the column number
										and the value (if a string) is the name of the function that should process the raw data value.
										for example $transforms = array( '5' => 'gnfac_cardinal_wind' )
*/

function gnfac_fetch_rpt_file($path, $offsets = 'lookup', $transforms = NULL, $truncate = FALSE , $data_only = FALSE ){
  if ( $offsets == 'lookup') {  // inserts $offsets and $transforms from the static file
		include( DRUPAL_ROOT.'/sites/all/modules/gnfac_d8/inc/rpt-offsets-transforms.inc.php');
  	$station_var = '_'.md5($path);
		$station = $$station_var ;
		
		$offsets = $station['offsets'];
		$transforms = $station['transforms'];
		$truncate = $station['truncate'];
  }
	   $node = \Drupal::routeMatch()->getParameter('node');

	
	$Data = @file_get_contents($path);
  \Drupal::logger('gnfac_d8')->info('Query to fetch ski area ( rpt ) file was made: '.$path);
	if ($Data === FALSE ){
		drupal_set_message('A needed weather data file could not be found: '. $path, WARNING);
		return;
	}else{

	  $tblrows = explode("\n", $Data);
    $header = array();
	  $rows = array();
    if ($truncate) { unset ($tblrows[0]);  unset ($tblrows[1]); unset ($tblrows[2]); /*$tblrows = array_slice($tblrows, 0 , -4); */ }

    foreach ($tblrows as $tblrow){
		  if ( strlen($tblrow) > ($offsets[count($offsets)-2 ]) // it is a genuinely long row, not spaces or header
		  &&  !strstr($tblrow, '------------')/*does not have a bunch of dashes*/ 
		  &&  !strpos( $tblrow, 'Page')/*does not have a 'Page' in the row */ ){
			
        $data_row_array = _rpt_split_rows(rtrim($tblrow) , $offsets);
			  if( countDigits($tblrow) < 7 ){
				  foreach($data_row_array as $key => $header_item ){
					  $header[$key] .= ' ';
					  if ( trim($header_item) && (!strstr( $header[$key] , trim($header_item) ) )   ){
					    $header[$key] .= trim($header_item) ;
					  }
          }
		    }else{ /* this is a data row, lotsa numbers */
			    if ( $transforms ){
					  foreach($transforms as $key => $transform){
						  $data_row_array[$key] = $transform(floatval($data_row_array[$key]));
					  }
				  }
				  $rows[] = $data_row_array;
		    }
	    }
	  }
	}
	if (count($rows > 50)) $rows = array_slice($rows, -50); 
  $rows = array_reverse($rows);
	$attributes['id'] = 'skiarea_tabdata';
	$node->field_recent_wx_data = gnfac_save_recent_wx_data( $header, $rows);
	$node->save();
	
	if ( $data_only == FALSE ){
	$markup = '<a href ="#nrcstblbottom">Jump to table bottom</a>'; 
		
		$variables = array( 
			'#type' => 'table',
		  '#header' => $header,
	    '#rows' => $rows,
	    '#attributes' => $attributes,
		  '#sticky' => TRUE,
	  );
		$markup .= drupal_render( $variables );
    $markup .= '<a name ="nrcstblbottom" class ="nrcstblbottom">.</a>';
		return $markup;
	}else{
		return $rows;
	}
}

function gnfac_num_format_2($value){
	if ( $value){
  	return number_format($value, 2);
	}
}


//
//    Two helper functions here
//

function _rpt_split_rows($row, $offsets){
	//drupal_set_message( var_export($offsets, TRUE) );
	foreach($offsets as $key => $offset){
		$start = ($key == 0) ? 0 : $offsets[$key - 1 ];
		$array[$key] = substr($row, $start , $offsets[$key] - $start);
	}
	
	return $array;
}

function countDigits( $str )
{
    return preg_match_all( "/[0-9]/", $str , $out);
}


function gnfac_cardinal_wind_dir($degrees){
	if (!is_numeric($degrees)) return;
	switch (true){
		
		case ($degrees >= 360-22.5 || $degrees < 22.5): $card = 'N'; break; 
		case ($degrees >=22.5 && $degrees < 67.5 ): $card = 'NE'; break;
		case ($degrees >=67.5 && $degrees < 112.5): $card = 'E'; break;
		case ($degrees >=112.5 && $degrees < 157.5): $card = 'SE'; break;
		case ($degrees >=157.5 && $degrees < 202.5): $card = 'S'; break;
		case ($degrees >=202.5 && $degrees < 247.5): $card = 'SW'; break;
		case ($degrees >= 247.5 && $degrees < 292.5): $card = 'W'; break;
		case ($degrees >=292.5 && $degrees < 337.5): $card ='NW'; break;
	
	
	}
	return $card . " - ". number_format($degrees, 0);
}

function avy_wx_charts_nrcs_block_view(){

	$node = \Drupal::routeMatch()->getParameter('node');
	$terms_array = array() ; //taxonomy_node_get_terms_by_vocabulary($node, '8');
	
	if (isset($node->field_nrcs_snotel_site->value) 
			&& $node->type->target_id == 'weather_station' 
			&& $node->field_weather_station_type->target_id == '434' )
	    {return TRUE;}else{
	     return FALSE;
	    }

	
	
}

function gnfac_current_year(){
	$year_minus_six_months = date('y', time() -  6*30*24*3600);
	$tid_year = $year_minus_six_months > 19 ?  $year_minus_six_months + 418 : $year_minus_six_months + 25 ;
	
	return (string) $tid_year;
}


function gnfac_sharing_links($node){
	$alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/'.$node->nid->value);
	?><div class="share_container">
		<span class='fb_share'><a href = "https://www.facebook.com/sharer/sharer.php?u=<?php echo "https://www.mtavalanche.com/".$alias; ?>" target="_blank" title = "Share via Facebook"><img src="/sites/all/themes/gnfac_theme/images/icons/facebook_32.png" /></a></span>
		
		<span class='twitter_share'><a href = "https://twitter.com/intent/tweet?text=<?php echo $node->title->value; ?>&via=AvalancheGuys&url=<?php echo "https://www.mtavalanche.com/".$alias; ?>" target ="_blank"><img src="/sites/all/themes/gnfac_theme/images/icons/twitter_32.png" title = "Tweet this page" /></a></span>
		
<span class='instagram'><a href = "https://instagram.com/mtavalanche/" target ="_blank"><img src="/sites/all/themes/gnfac_theme/images/icons/instagram_32.png" title = "View MT Avalanche photo stream" /></a></span>
<span class='mail'><a href = "mailto:?subject=Avalanche Center Image or Photo" target ="_blank"><img src="/sites/all/themes/gnfac_theme/images/icons/email-black-sm.png" title = "Email this item" /></a></span>	
	
	</div>
	<?php 
}

 

/*Zone 0 = Bridger Range
Zone 1 = Northern Gallatin Range
Zone 2 = Lionhead Area
Zone 3 = Cooke City
Zone 4 = Northern Madison Range
Zone 5 = Southern Madison Range
Zone 6 = Southern Gallatin Range  
 */
function advisory_caaml_build_xml(){
  
  $advisory_regions = array(
    '23' => array( 
      'name' =>  'Bridger Range',
      'id' => '0',
			'tid' => '23',
      ),
    '25' => array( 
      'name' =>  'Northern Gallatin',
      'id' => '1',
			'tid' => '25',
      ),   
    '29' => array( 
      'name' =>  'Lionhead Area',
      'id' => '2',
			'tid' => '29',
      ),   
    '28' => array( 
      'name' =>  'Cooke City',
      'id' => '3',
			'tid' => '28',
      ),  
    '24' => array( 
      'name' =>  'Northern Madison',
      'id' => '4',
			'tid' => '24',
      ),    
    '26' => array( 
      'name' =>  'Southern Madison',
      'id' => '5',
			'tid' => '26',
      ),
    '27' => array( 
      'name' =>  'Southern Gallatin',
      'id' => '6',
			'tid' => '27',
      ), 
    );
    
$advisory_msgs = array(
	'None' => '0',
  'Low' => '1',
  'Moderate' => '2',
  'Considerable' => '3',
  'High' => '4',
  'Extreme' => '5',
  '' => '0'
  );
	
	$advisory = gnfac_current_advisory('node');
	
	//kint($advisory);

		$advisory_region_groups = $advisory->field_region_group_1->getValue() ;
		//  \Drupal::logger('my_module')->notice($message);
		foreach( $advisory_region_groups as $key2 => $region_group) {
		  $fc = \Drupal\field_collection\Entity\FieldCollectionItem::load($region_group['value']);
			
	  	foreach($fc->field_applicable_regions->getValue() as $region_num){
	
		//  
		// Save the feild collections into the $advisory_regions array for use below
		//
		//  mainly $field-> image and node0bject->discussion .... 
  
  //$images = array();
  
   $zone_name = $advisory_regions[$region_num['target_id']]['name'] ;  //name opf advisory zone
   $zone_id = $advisory_regions[$region_num['target_id']]['id'];
   $valid_date = date( 'c' , strtotime($advisory->field_valid_dates->value)  - 7*60*60 ); kint (strtotime($advisory->field_valid_dates->value) - 7*60*60);
   $danger = $advisory_msgs[ $fc->field_regional_hazard_rating->value ];
	 $report_date = date( 'c' , $advisory->created->value); //kint ($advisory->created->value); 
	 $bottom_line = $fc->field_regional_discussion->summary ;
	 $problem_type = $fc->field_problem_type->view('full');
	 //exit();
// Begin code, adapted from Cpeck  

   $filename = DRUPAL_ROOT . "/sites/default/files/xml/".str_replace(' ' , '_', $zone_name)."_Forecast.xml";
   $home_url= "https://www.mtavalanche.com";
   
  // Write CAAML file. Ref=http://caaml.org/Schemas/V5.0/Profiles/BulletinUS/
  $f = fopen($filename,'w');
  fwrite($f, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
  fwrite($f, "<Bulletin");
  fwrite($f, "  xmlns=\"http://caaml.org/Schemas/V5.0/Profiles/BulletinUS\"");
  fwrite($f, "  xmlns:gml=\"http://www.opengis.net/gml\"");
  fwrite($f, "  xmlns:xlink=\"http://www.w3.org/1999/xlink\"");
  fwrite($f, "  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"");
  fwrite($f, "  xsi:schemaLocation=\"http://caaml.org/Schemas/V5.0/Profiles/BulletinUS");
  fwrite($f, "    http://caaml.org/Schemas/V5.0/Profiles/BulletinUS/CAAMLv5_BulletinUS.xsd\"");
  fwrite($f, "  gml:id=\"BulletinID01\"");
  fwrite($f, ">\n");
  fwrite($f, "  <metaDataProperty>\n");
  fwrite($f, "    <MetaData>\n");
  fwrite($f, "      <dateTimeReport>$report_date</dateTimeReport>\n");
  fwrite($f, "      <srcRef>\n");
  fwrite($f, "        <Operation gml:id=\"GNFAC\">\n");
  fwrite($f, "          <name>Gallatin National Forest Avalanche Center</name>\n");
	// contact person
  fwrite($f, "        </Operation>\n");
  fwrite($f, "      </srcRef>\n");

  fwrite($f, "      <srcURL>".htmlentities("$home_url/advisory")."</srcURL>\n");
  fwrite($f, "      <comment>Complete Avalanche Forecast for Gallatin NF Advisory Regions</comment>\n");
  fwrite($f, "    </MetaData>\n");
  fwrite($f, "  </metaDataProperty>\n");
  fwrite($f, "  <validTime>\n");
  fwrite($f, "    <TimePeriod>\n");
  
  // include timezone offset for CAAML

  fwrite($f, "      <beginPosition>".$report_date."</beginPosition>\n");
  fwrite($f, "      <endPosition>".date('c',strtotime($valid_date))."</endPosition>\n");
  fwrite($f, "    </TimePeriod>\n");
  fwrite($f, "  </validTime>\n");
  fwrite($f, "  <bulletinResultsOf>\n");
  fwrite($f, "    <BulletinMeasurements>\n");
 // SAMPLE MEDIA
  if ( count( $advisory->field_images ) ){
		
    foreach ($advisory->field_images->getValue() as $image_id){
			$image_node = Drupal\node\Entity\Node::load($image_id['target_id']);
    fwrite($f, "          <customData>\n");
    fwrite($f, "            <Media>\n");
    fwrite($f, "              <uRL>".ImageStyle::load('medium')->buildUrl($image_node->field_image_file->entity->getFileUri())."</uRL>\n");
    fwrite($f, "              <description><![CDATA[".$image_node->title->value. " ". $image_node->body->value."]]></description>\n");
    fwrite($f, "            </Media>\n");
    fwrite($f, "          </customData>\n");
    }
  }
  fwrite($f, "      <bulletinType>Bulletin</bulletinType>\n");

  fwrite($f, "      <dangerRatings>\n");
  fwrite($f, "        <DangerRatingSingle>\n");
  fwrite($f, "          <mainValue>$danger</mainValue>\n");
  fwrite($f, "          <comment>$bottom_line</comment>\n");
  fwrite($f, "        </DangerRatingSingle>\n");
  fwrite($f, "      </dangerRatings>\n");
  fwrite($f, "      <avProblems>\n");
  fwrite($f, "        <avProblem>\n");
	fwrite($f, "          <type>" . trim(strip_tags(render($problem_type))) . "</type>\n" );	
  fwrite($f, "        </avProblem>\n");
  fwrite($f, "      </avProblems>\n");
  fwrite($f, "      <avSnowComment><![CDATA[". $fc->field_regional_discussion->value."]]></avSnowComment>\n");
  fwrite($f, "    </BulletinMeasurements>\n");
  fwrite($f, "  </bulletinResultsOf>\n");
  fwrite($f, "  <Region gml:id=\"$zone_id\">\n");
  fwrite($f, "    <name>$zone_name</name>\n");
  fwrite($f, "    <regionSubType>Forecast Zone</regionSubType>\n");
  fwrite($f, "  </Region>\n");


  fwrite($f, "  <locRef xlink:href=\"ForecastRegionID$zone_id\"/>\n");
  fwrite($f, "</Bulletin>\n");
  fclose($f);
	}
}

  //reset timezone back to whatever the server had
  date_default_timezone_set($reset);
	
  //}
 }


 function advisory_caaml_push_xml(){
     $advisory_regions = array(
     '0' => array( 
       'name' =>  'Bridger Range',
       'id' => '0',
       'db_val' => 'field_bridger_haz',
       ),
     '1' => array( 
       'name' =>  'Northern Gallatin',
       'id' => '1',
       'db_val' => 'field_n_gall',
       ),   
     '2' => array( 
       'name' =>  'Lionhead Area',
       'id' => '2',
       'db_val' => 'field_lionhead',
       ),   
     '3' => array( 
       'name' =>  'Cooke City',
       'id' => '3',
       'db_val' => 'field_cooke'
       ),  
     '4' => array( 
       'name' =>  'Northern Madison',
       'id' => '4',
       'db_val' => 'field_n_madison',
       ),    
     '5' => array( 
       'name' =>  'Southern Madison',
       'id' => '5',
       'db_val' => 'field_s_madison',
       ),
     '6' => array( 
       'name' =>  'Southern Gallatin',
       'id' => '6',
       'db_val' => 'field_s_gall',
       ), 
     );
    
   foreach($advisory_regions as $region){
    
     $filename = "/sites/default/files/xml/".str_replace(' ' , '_', $region['name'])."_Forecast.xml";
     //print_r($filename."<br />");
     $ch = curl_init();
     $data = array('centerID' => 'GNFAC', 'xml_file1' => new CurlFile($_SERVER["DOCUMENT_ROOT"] . $filename) );
     curl_setopt($ch, CURLOPT_URL, 'http://national-map.jhavalanche.org/upload_caaml.php');
     curl_setopt($ch, CURLOPT_POST, 1);
     curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
     curl_setopt($ch, CURLOPT_USERPWD, 'avycenter:ca&8aml'); 
     //curl_setopt($ch, CURLOPT_STDERR, $fp);   
     $server_output = curl_exec($ch);
     print_r("<br /> <a href =' ".$filename."'>" . $filename ."</a>" );
     if ($server_output === FALSE) {
       drupal_set_message ('CAAML upload failed with error ' . curl_error($ch));
     }

     $curlinfo = curl_getinfo($ch);    //if you want to show the information
    
     curl_close($ch);
     //var_dump($curlinfo);
   }
 return;
 }
 